### ISSUE TITLE
Manually start program if disabled

### ISSUE THREAD

**Issue by gafk** [rianadon/opensprinkler-card#18]
I would like to be able to start my program(s) manually even if they are disabled. Currently the "Play button" is greyed out and I have to enable the program first using the switch. 

As far as I understand, it is possible to call the opensprinkler.run service even if the program is disabled to start the program once manually.

Any thoughts or reasons why this is not working? Am I missing something?

```
type: custom:opensprinkler-card
device: 60a146f0e7cae794128d151fc69e362e
name: Rasensprenger
extra_entities:
  - switch.dr_opensprinkler_kurz_program_enabled
  - binary_sensor.dr_opensprinkler_kurz_program_running
input_number:
  entity: input_number.dr_opensprinkler_dauer
  name: Dauer

```

"Play" greyed out:

![grafik](https://user-images.githubusercontent.com/72245547/181707354-f64bf3c7-c193-413c-b547-e843cd804552.png)

"Play" working only when switch enabled:

![grafik](https://user-images.githubusercontent.com/72245547/181707419-05aca365-37de-4722-9ca3-880d612726ee.png)
