### ISSUE TITLE
input_number not working

### ISSUE THREAD

**Issue by woobenjamin** [rianadon/opensprinkler-card#2]
I'm not sure if this is a opensprinkler-card issue or a numberbox-card issue. 
I have the following opensprinkler-card config:
```
type: custom:opensprinkler-card
device: abcdefghijklmnopqrstuvwxyz
name: Sprinklers
hide_disabled: true
bars:
  bar_foreground: green
  icon: hass:sprinkler
  active_icon: hass:sprinkler-variant
input_number:
  entity: input_number.slider
  type: custom:numberbox-card
  unit: m
  icon: mdi:timelapse
card_stations:
  - sensor.curb_station_status
  - sensor.front_yard_station_status
  - sensor.side_yard_station_status
  - sensor.s_flower_bed_station_status
```
For input_number, I have the following in configuration.yaml
`input_number: !include input_numbers.yaml`
In input_numbers.yaml I have the following:
```
slider:
  name: Watering Duration
  initial: 15 # in minutes
  min: 0
  max: 30
  step: 5
  # You can also use mode: box
```
But when I click the run button (right arrow), I see only 1m on the runtime:
![image](https://user-images.githubusercontent.com/45885373/123308963-2e04f280-d4d9-11eb-80b3-309803e49938.png)

My apologies if this is not an opensprinkler-card issue.
